package api

import (
	"reflect"

	"github.com/drekle/dns-server/pkg/lib/go/v1"
	"github.com/miekg/dns"
)

func getRRfromAPIRecord(record *v1.ResourceRecord) dns.RR {
	switch reflect.TypeOf(record.Record).String() {
	case "*v1.ResourceRecord_A":
		return GetARecord(record)
	case "*v1.ResourceRecord_Aaaa":
		return GetAaaaRecord(record)
	case "*v1.ResourceRecord_Afsdb":
		return GetAfsdbRecord(record)
	case "*v1.ResourceRecord_Avc":
		return GetAvcRecord(record)
	case "*v1.ResourceRecord_Caa":
		return GetCaaRecord(record)
	case "*v1.ResourceRecord_Cdnskey":
		return GetCdnskeyRecord(record)
	case "*v1.ResourceRecord_Cds":
		return GetCdsRecord(record)
	case "*v1.ResourceRecord_Cert":
		return GetCertRecord(record)
	case "*v1.ResourceRecord_Cname":
		return GetCnameRecord(record)
	case "*v1.ResourceRecord_Csync":
		return GetCsyncRecord(record)
	case "*v1.ResourceRecord_Dhcid":
		return GetDhcidRecord(record)
	case "*v1.ResourceRecord_Dlv":
		return GetDlvRecord(record)
	case "*v1.ResourceRecord_Dname":
		return GetDnameRecord(record)
	case "*v1.ResourceRecord_Dnskey":
		return GetDnskeyRecord(record)
	case "*v1.ResourceRecord_Ds":
		return GetDsRecord(record)
	case "*v1.ResourceRecord_Eid":
		return GetEidRecord(record)
	case "*v1.ResourceRecord_Eui48":
		return GetEui48Record(record)
	case "*v1.ResourceRecord_Eui64":
		return GetEui64Record(record)
	case "*v1.ResourceRecord_Gid":
		return GetGidRecord(record)
	case "*v1.ResourceRecord_Gpos":
		return GetGposRecord(record)
	case "*v1.ResourceRecord_Hinfo":
		return GetHinfoRecord(record)
	case "*v1.ResourceRecord_Hip":
		return GetHipRecord(record)
	case "*v1.ResourceRecord_Key":
		return GetKeyRecord(record)
	case "*v1.ResourceRecord_Kx":
		return GetKxRecord(record)
	case "*v1.ResourceRecord_L32":
		return GetL32Record(record)
	case "*v1.ResourceRecord_L64":
		return GetL64Record(record)
	case "*v1.ResourceRecord_Loc":
		return GetLocRecord(record)
	case "*v1.ResourceRecord_Lp":
		return GetLpRecord(record)
	case "*v1.ResourceRecord_Mb":
		return GetMbRecord(record)
	case "*v1.ResourceRecord_Md":
		return GetMdRecord(record)
	case "*v1.ResourceRecord_Mf":
		return GetMfRecord(record)
	case "*v1.ResourceRecord_Mg":
		return GetMgRecord(record)
	case "*v1.ResourceRecord_Minfo":
		return GetMinfoRecord(record)
	case "*v1.ResourceRecord_Mr":
		return GetMrRecord(record)
	case "*v1.ResourceRecord_Mx":
		return GetMxRecord(record)
	case "*v1.ResourceRecord_Naptr":
		return GetNaptrRecord(record)
	case "*v1.ResourceRecord_Nid":
		return GetNidRecord(record)
	case "*v1.ResourceRecord_Nimloc":
		return GetNimlocRecord(record)
	case "*v1.ResourceRecord_Ninfo":
		return GetNinfoRecord(record)
	case "*v1.ResourceRecord_Ns":
		return GetNsRecord(record)
	case "*v1.ResourceRecord_Nsapptr":
		return GetNsapptrRecord(record)
	case "*v1.ResourceRecord_Nsec":
		return GetNsecRecord(record)
	case "*v1.ResourceRecord_Nsec3":
		return GetNsec3Record(record)
	case "*v1.ResourceRecord_Nsec3Param":
		return GetNsec3ParamRecord(record)
	case "*v1.ResourceRecord_Openpgpkey":
		return GetOpenpgpkeyRecord(record)
	case "*v1.ResourceRecord_Opt":
		return GetOptRecord(record)
	case "*v1.ResourceRecord_Ptr":
		return GetPtrRecord(record)
	case "*v1.ResourceRecord_Px":
		return GetPxRecord(record)
	case "*v1.ResourceRecord_Rkey":
		return GetRkeyRecord(record)
	case "*v1.ResourceRecord_Rp":
		return GetRpRecord(record)
	case "*v1.ResourceRecord_Rrsig":
		return GetRrsigRecord(record)
	case "*v1.ResourceRecord_Rt":
		return GetRtRecord(record)
	case "*v1.ResourceRecord_Sig":
		return GetSigRecord(record)
	case "*v1.ResourceRecord_Smimea":
		return GetSmimeaRecord(record)
	case "*v1.ResourceRecord_Soa":
		return GetSoaRecord(record)
	case "*v1.ResourceRecord_Spf":
		return GetSpfRecord(record)
	case "*v1.ResourceRecord_Srv":
		return GetSrvRecord(record)
	case "*v1.ResourceRecord_Sshfp":
		return GetSshfpRecord(record)
	case "*v1.ResourceRecord_Ta":
		return GetTaRecord(record)
	case "*v1.ResourceRecord_Talink":
		return GetTalinkRecord(record)
	case "*v1.ResourceRecord_Tkey":
		return GetTkeyRecord(record)
	case "*v1.ResourceRecord_Tlsa":
		return GetTlsaRecord(record)
	case "*v1.ResourceRecord_Tsig":
		return GetTsigRecord(record)
	case "*v1.ResourceRecord_Txt":
		return GetTxtRecord(record)
	case "*v1.ResourceRecord_Uid":
		return GetUidRecord(record)
	case "*v1.ResourceRecord_Uinfo":
		return GetUinfoRecord(record)
	case "*v1.ResourceRecord_Uri":
		return GetUriRecord(record)
	case "*v1.ResourceRecord_X25":
		return GetX25Record(record)
	}
	return nil
}
